<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260628214157 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE domaine (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, icone VARCHAR(255) NOT NULL, strategie_key VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_78AF0ACC989D9B62 ON domaine (slug)');
        $this->addSql('CREATE TABLE exercice (id UUID NOT NULL, enonce TEXT NOT NULL, outil_suggere JSON DEFAULT NULL, rendu_utilisateur TEXT DEFAULT NULL, feedback_ia TEXT DEFAULT NULL, feedback_score INT DEFAULT NULL, decision VARCHAR(255) DEFAULT NULL, statut_evaluation VARCHAR(255) NOT NULL, session_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E418C74D613FECDF ON exercice (session_id)');
        $this->addSql('CREATE TABLE micro_etape (id UUID NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT NOT NULL, type VARCHAR(255) NOT NULL, outil_externe JSON DEFAULT NULL, rendu_utilisateur TEXT DEFAULT NULL, feedback_ia TEXT DEFAULT NULL, statut VARCHAR(255) NOT NULL, ordre INT NOT NULL, debloquee_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, derniere_piste_ia TEXT DEFAULT NULL, derniere_piste_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, projet_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_38F56A0BC18272 ON micro_etape (projet_id)');
        $this->addSql('CREATE INDEX IDX_38F56A0BE564F0BF ON micro_etape (statut)');
        $this->addSql('CREATE INDEX IDX_38F56A0B737992C9 ON micro_etape (ordre)');
        $this->addSql('CREATE TABLE parcours (id UUID NOT NULL, titre VARCHAR(255) NOT NULL, objectif TEXT NOT NULL, niveau VARCHAR(255) NOT NULL, duree_cible_semaines INT NOT NULL, statut VARCHAR(255) NOT NULL, derniere_eval_surprise_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id UUID NOT NULL, domaine_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_99B1DEE34272FC9F ON parcours (domaine_id)');
        $this->addSql('CREATE INDEX IDX_99B1DEE3A76ED395 ON parcours (user_id)');
        $this->addSql('CREATE INDEX IDX_99B1DEE3E564F0BF ON parcours (statut)');
        $this->addSql('CREATE INDEX IDX_99B1DEE34AF38FD1 ON parcours (deleted_at)');
        $this->addSql('CREATE TABLE progression (id UUID NOT NULL, score_consolidation INT NOT NULL, score_projet INT NOT NULL, ressources_total INT NOT NULL, ressources_consolidees INT NOT NULL, sujets_fragiles JSON NOT NULL, derniere_activite TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parcours_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D5B250736E38C0DB ON progression (parcours_id)');
        $this->addSql('CREATE TABLE projet_fil_rouge (id UUID NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT NOT NULL, statut VARCHAR(255) NOT NULL, prompt_version VARCHAR(255) NOT NULL, reponse_ia_brute JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parcours_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_31EDBA816E38C0DB ON projet_fil_rouge (parcours_id)');
        $this->addSql('CREATE TABLE question (id UUID NOT NULL, texte TEXT NOT NULL, reponse_utilisateur TEXT DEFAULT NULL, feedback_ia TEXT DEFAULT NULL, feedback_score INT DEFAULT NULL, decision VARCHAR(255) DEFAULT NULL, validee BOOLEAN NOT NULL, statut_evaluation VARCHAR(255) NOT NULL, ordre INT NOT NULL, session_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6F7494E613FECDF ON question (session_id)');
        $this->addSql('CREATE INDEX IDX_B6F7494E737992C9 ON question (ordre)');
        $this->addSql('CREATE TABLE ressource (id UUID NOT NULL, titre VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, ordre INT NOT NULL, statut VARCHAR(255) NOT NULL, duree_estimee_minutes INT DEFAULT NULL, pomodoros_suggeres INT DEFAULT NULL, viewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, consolidated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parcours_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_939F45446E38C0DB ON ressource (parcours_id)');
        $this->addSql('CREATE INDEX IDX_939F4544E564F0BF ON ressource (statut)');
        $this->addSql('CREATE INDEX IDX_939F4544737992C9 ON ressource (ordre)');
        $this->addSql('CREATE TABLE revision_espacee (id UUID NOT NULL, iteration INT NOT NULL, date_prevue DATE NOT NULL, completee_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, score INT DEFAULT NULL, reporte_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ressource_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5FBA02D2FC6CD52A ON revision_espacee (ressource_id)');
        $this->addSql('CREATE INDEX IDX_5FBA02D2A76ED395 ON revision_espacee (user_id)');
        $this->addSql('CREATE INDEX IDX_5FBA02D2EE522B99 ON revision_espacee (date_prevue)');
        $this->addSql('CREATE INDEX IDX_5FBA02D2ECB2B65F ON revision_espacee (completee_at)');
        $this->addSql('CREATE TABLE session_consolidation (id UUID NOT NULL, type VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, prompt_version VARCHAR(255) NOT NULL, modele_ia VARCHAR(255) DEFAULT NULL, reponse_ia_brute JSON DEFAULT NULL, generation_error TEXT DEFAULT NULL, regeneration_reason TEXT DEFAULT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ressource_id UUID NOT NULL, trace_apprentissage_id UUID DEFAULT NULL, parent_session_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A595B39040242B47 ON session_consolidation (trace_apprentissage_id)');
        $this->addSql('CREATE INDEX IDX_A595B390267C688F ON session_consolidation (parent_session_id)');
        $this->addSql('CREATE INDEX IDX_A595B390FC6CD52A ON session_consolidation (ressource_id)');
        $this->addSql('CREATE INDEX IDX_A595B390E564F0BF ON session_consolidation (statut)');
        $this->addSql('CREATE INDEX IDX_A595B3908CDE5729 ON session_consolidation (type)');
        $this->addSql('CREATE TABLE trace_apprentissage (id UUID NOT NULL, compris_par_utilisateur TEXT DEFAULT NULL, points_flous TEXT DEFAULT NULL, application_possible TEXT DEFAULT NULL, confiance_utilisateur INT DEFAULT NULL, pomodoros_effectues INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ressource_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E58FBE37FC6CD52A ON trace_apprentissage (ressource_id)');
        $this->addSql('CREATE INDEX IDX_E58FBE37A76ED395 ON trace_apprentissage (user_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, prenom VARCHAR(100) NOT NULL, nom VARCHAR(100) NOT NULL, niveau VARCHAR(255) NOT NULL, plan VARCHAR(255) NOT NULL, mode_accompagnement VARCHAR(255) NOT NULL, langue VARCHAR(2) NOT NULL, avatar_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE INDEX IDX_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE INDEX IDX_8D93D6494AF38FD1 ON "user" (deleted_at)');
        $this->addSql('ALTER TABLE exercice ADD CONSTRAINT FK_E418C74D613FECDF FOREIGN KEY (session_id) REFERENCES session_consolidation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE micro_etape ADD CONSTRAINT FK_38F56A0BC18272 FOREIGN KEY (projet_id) REFERENCES projet_fil_rouge (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE parcours ADD CONSTRAINT FK_99B1DEE3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE parcours ADD CONSTRAINT FK_99B1DEE34272FC9F FOREIGN KEY (domaine_id) REFERENCES domaine (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE progression ADD CONSTRAINT FK_D5B250736E38C0DB FOREIGN KEY (parcours_id) REFERENCES parcours (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projet_fil_rouge ADD CONSTRAINT FK_31EDBA816E38C0DB FOREIGN KEY (parcours_id) REFERENCES parcours (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494E613FECDF FOREIGN KEY (session_id) REFERENCES session_consolidation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ressource ADD CONSTRAINT FK_939F45446E38C0DB FOREIGN KEY (parcours_id) REFERENCES parcours (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE revision_espacee ADD CONSTRAINT FK_5FBA02D2FC6CD52A FOREIGN KEY (ressource_id) REFERENCES ressource (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE revision_espacee ADD CONSTRAINT FK_5FBA02D2A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_consolidation ADD CONSTRAINT FK_A595B390FC6CD52A FOREIGN KEY (ressource_id) REFERENCES ressource (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_consolidation ADD CONSTRAINT FK_A595B39040242B47 FOREIGN KEY (trace_apprentissage_id) REFERENCES trace_apprentissage (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_consolidation ADD CONSTRAINT FK_A595B390267C688F FOREIGN KEY (parent_session_id) REFERENCES session_consolidation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trace_apprentissage ADD CONSTRAINT FK_E58FBE37FC6CD52A FOREIGN KEY (ressource_id) REFERENCES ressource (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trace_apprentissage ADD CONSTRAINT FK_E58FBE37A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercice DROP CONSTRAINT FK_E418C74D613FECDF');
        $this->addSql('ALTER TABLE micro_etape DROP CONSTRAINT FK_38F56A0BC18272');
        $this->addSql('ALTER TABLE parcours DROP CONSTRAINT FK_99B1DEE3A76ED395');
        $this->addSql('ALTER TABLE parcours DROP CONSTRAINT FK_99B1DEE34272FC9F');
        $this->addSql('ALTER TABLE progression DROP CONSTRAINT FK_D5B250736E38C0DB');
        $this->addSql('ALTER TABLE projet_fil_rouge DROP CONSTRAINT FK_31EDBA816E38C0DB');
        $this->addSql('ALTER TABLE question DROP CONSTRAINT FK_B6F7494E613FECDF');
        $this->addSql('ALTER TABLE ressource DROP CONSTRAINT FK_939F45446E38C0DB');
        $this->addSql('ALTER TABLE revision_espacee DROP CONSTRAINT FK_5FBA02D2FC6CD52A');
        $this->addSql('ALTER TABLE revision_espacee DROP CONSTRAINT FK_5FBA02D2A76ED395');
        $this->addSql('ALTER TABLE session_consolidation DROP CONSTRAINT FK_A595B390FC6CD52A');
        $this->addSql('ALTER TABLE session_consolidation DROP CONSTRAINT FK_A595B39040242B47');
        $this->addSql('ALTER TABLE session_consolidation DROP CONSTRAINT FK_A595B390267C688F');
        $this->addSql('ALTER TABLE trace_apprentissage DROP CONSTRAINT FK_E58FBE37FC6CD52A');
        $this->addSql('ALTER TABLE trace_apprentissage DROP CONSTRAINT FK_E58FBE37A76ED395');
        $this->addSql('DROP TABLE domaine');
        $this->addSql('DROP TABLE exercice');
        $this->addSql('DROP TABLE micro_etape');
        $this->addSql('DROP TABLE parcours');
        $this->addSql('DROP TABLE progression');
        $this->addSql('DROP TABLE projet_fil_rouge');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE ressource');
        $this->addSql('DROP TABLE revision_espacee');
        $this->addSql('DROP TABLE session_consolidation');
        $this->addSql('DROP TABLE trace_apprentissage');
        $this->addSql('DROP TABLE "user"');
    }
}
